### ISSUE TITLE
onSubmit is being called before preSubmit

### ISSUE THREAD

**Issue by anaspk** [react-tools/react-form#302]
I am on v3.5.1 and I am experiencing this weird behavior where the preSubmit is called after onSubmit. You can see this in action in this codesandbox: https://codesandbox.io/s/6n2vnyj2q3

Enter a value in the text field and hit submit. Check the console. You will see that the log statement from onSubmit is printed before the one from preSubmit. Also, onSubmit receives the original value, not the one that is returned from preSubmit. Am I missing something? I am pretty sure that it was working correctly a few versions ago, specifically in v3.4.4

**Comment by daviscabral** [comment]
Also confirmed that is not working as expected on v3.5.3.

**Comment by joepuzzo** [comment]
This is fixed in latest release

**Comment by anaspk** [comment]
Thanks a lot @joepuzzo . Now preSubmit is called before onSubmit which is correct. But onSubmit still gets the original values and not the ones returned from preSubmit. No?

**Comment by ThomasLabstep** [comment]
Can confirm preSubmit is called AFTER onSubmit.
